/** Maps quiz question ID → array of study term IDs */
export const questionRelatedTerms: Record<string, string[]> = {
  "storage-1": ["efs", "ebs", "s3", "block-storage", "object-storage"],
  "storage-2": ["s3", "s3-intelligent-tiering"],
  "storage-3": ["ebs", "s3", "efs", "block-storage"],
  "storage-4": ["s3", "s3-glacier", "s3-intelligent-tiering"],
  "storage-5": ["fsx-windows", "efs"],
  "storage-6": ["s3", "vpc", "privatelink"],
  "storage-7": ["fsx-lustre", "efs"],
  "storage-8": ["s3-intelligent-tiering", "s3"],
  "storage-9": ["s3"],
  "storage-10": ["snowball-edge", "s3"],
  "storage-11": ["s3"],
  "compute-1": ["lambda", "serverless", "ec2"],
  "compute-2": ["reserved-instances", "spot-instance", "ec2"],
  "compute-3": ["auto-scaling-group", "auto-scaling", "load-balancer"],
  "compute-4": ["fargate", "ecs", "ec2"],
  "compute-5": ["ec2"],
  "compute-6": ["spot-instance", "reserved-instances", "ec2"],
  "compute-7": ["rds", "lambda"],
  "compute-8": ["eks", "ecs", "fargate"],
  "compute-9": ["alb", "auto-scaling-group", "load-balancer"],
  "compute-10": ["batch", "lambda"],
  "network-1": ["route-53", "alb", "load-balancer", "cloudfront"],
  "network-2": ["nat-gateway", "internet-gateway", "private-subnet", "vpc"],
  "network-3": ["alb", "nlb", "load-balancer"],
  "network-4": ["vpc-peering", "transit-gateway"],
  "network-5": ["direct-connect", "vpc"],
  "network-6": ["waf", "shield", "guardduty", "cloudfront"],
  "network-7": ["security-group", "vpc", "subnet"],
  "network-8": ["cloudfront", "cdn", "route-53"],
  "network-9": ["transit-gateway", "vpc-peering", "nat-gateway"],
  "network-10": ["route-53", "high-availability", "fault-tolerance"],
  "network-11": ["vpc", "privatelink", "s3"],
  "database-1": ["dynamodb", "rds", "aurora", "redshift"],
};
